### ISSUE TITLE
command 'extension.addComment' not found

### ISSUE THREAD

**Issue by BasvanH** [shishirui/phpdoc-comment-vscode-plugin#1]
Hello,

I installed and enabled the plugin. When using the shortcut of command pallet and select 'Add PHPDoc Comment', I get the following error:

`command 'extension.addComment' not found`

Have restarted and updated VSC without success.

Kind regards,
Bastiaan

**Comment by zendzo** [comment]
i have the same issue here, just installed and run the shortcut.

**Comment by MushuLeDragon** [comment]
Same for me. Any solutions or advise ?

**Comment by navinweb** [comment]
Same. Not found solution

**Comment by shishirui** [comment]
@zendzo @MushuLeDragon @navinweb 

SORRY. This because a bug. I have fixed it. Please update/reinstall the plugin.

**Comment by BasvanH** [comment]
Confimed, now it works.

**Comment by navinweb** [comment]
@shishirui Works like a charm! Nice work!
