### ISSUE TITLE
Please  select a PHP signature

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [shishirui/phpdoc-comment-vscode-plugin#12]
That appears when i try to use it, it might be obvius that I dont know what I need to change and where?

**Comment by Zabanya** [comment]
parameter signature. A class / function / variable; etc

**Comment by shishirui** [comment]
> parameter signature. A class / function / variable; etc

This is the correct answer.

**Comment by mg169706** [comment]
> parameter signature. A class / function / variable; etc

What does this even mean?!? Do we need to put something in settings.json? What format? Please document this properly. Thanks.

**Comment by ChaerilM** [comment]
> 
> 
> > parameter signature. A class / function / variable; etc
> 
> What does this even mean?!? Do we need to put something in settings.json? What format? Please document this properly. Thanks.

https://lmgtfy.com/?q=PARAMETER+SIGNATURE+PHP
https://stackoverflow.com/questions/16219888/what-is-a-parameter-signature-in-php

```php
class LMGTFY  {  //signature

    function Google ($search){ //signature
        var $result //signature

    }
}
```

put cursor on the signature then run the command

**Comment by locvfx** [comment]
Example you want to add Comment Block to a function, you need to put your Cursor after a function declaration, 
then press ctr-shift-i

function name($param) **[PUT YOUR CURSOR HERE]**
{ 
     //
}

**Comment by yeasir2148** [comment]
I am getting the same meesage when trying to add docblock for a class variable.

`public string $baseText;`

When place the cursor at the end of that line and do `ctrl+shift+i`, the extension throws a message `please select a PHP signature`.

Not sure what to do

**Comment by Lukid** [comment]
yes the problem seems to show up when you use type declarations for a class property.

**Comment by jrcii** [comment]
> Example you want to add Comment Block to a function, you need to put your Cursor after a function declaration, then press ctr-shift-i
> 
> function name($param) **[PUT YOUR CURSOR HERE]** { // }

This is what should pop up in the notification, how would a user of this extension know this? You could have implemented this by requiring a selection of the signature, or before it. Include this example as well https://github.com/shishirui/phpdoc-comment-vscode-plugin/issues/12#issuecomment-673480783

**Comment by andyg2** [comment]
"Please select a PHP signature" is technically accurate however it is not commonly used terminology and even Google searches for 'what is a php signature' or just 'php signature' yield little assistance. In fact 'php signature' is rewritten to 'pgp signature' by google,

Consider using: "Not found, select the first line of your function, class or method"

**Comment by chrislp** [comment]
Given that in my case the "parameter signature. A class / function / variable; etc" was present and for me the right answer would have been: _Don't put the cursor in the line above the signature, where you want the comment, but after the signature, where you don't want the comment_, the comments in this issue are very disrespectful. 
If you don't want to help, you don't have to answer. If you want to help, you don't have to behave like a brat.
