### ISSUE TITLE
How to fix - Please select a PHP signature?

### ISSUE THREAD

**Issue by cukulkarni** [shishirui/phpdoc-comment-vscode-plugin#14]
I installed plugin on VS Code V-1.43.2. When I try to use it using Ctrl+I I get an error on toast " Please select a PHP signature".

Please help.

**Comment by cukulkarni** [comment]
One more note, I read all the past closed issues and I did not find a solution or hint. May be I am not able to relate it.

**Comment by cukulkarni** [comment]
Okay, I found it and fixed it.

**Comment by shivdhwaj** [comment]
> Okay, I found it and fixed it.

How you solved it? I need help for the same

**Comment by myfender** [comment]
Hi, what is the solution?
