### ISSUE TITLE
Automatically activate when new function is entered

### ISSUE THREAD

**Issue by amanpatel** [shishirui/phpdoc-comment-vscode-plugin#2]
Can this plugin auto-insert the phpdoc tags when a new function is created and the "{" key is entered ?

Basically, you'd enter the function signature like so:

`function addTwoNumbers(int $a, int $b) {`

(pressing enter would insert the phpdoc).

**Comment by phptek** [comment]
In Netbeans, as soon as you're finished typing the method signature, it starts to auto-generate the docblock and auto-inserts it upon hitting "Enter" after one (or possibly the second) paren. With this extension (at least on a MBP) I need to:

1). Highlight the method sig
2) Hit Fn + F1
