### ISSUE TITLE
Parameters appear "mixed"

### ISSUE THREAD

**Issue by Ouster-dev** [shishirui/phpdoc-comment-vscode-plugin#27]
Hello,

I have a problem, it seems that when i create a function with typed parameter the extension don't care of the type

```PHP
 * debugPrint
 *
 * @param  mixed $message
 * @param  mixed $stopAfterDebug
 * @return void
 */
function debugPrint(string $message, bool $stopAfterDebug = false) : void {
```

Is this normal or do i need to put the type by myself ?

**Comment by shishirui** [comment]
yes.

**Comment by hellmediadev** [comment]
Could you please explain why the plugin does not add `* @param  string $message`
