### ISSUE TITLE
Plugin not working for classes

### ISSUE THREAD

**Issue by FreddyCrugger** [shishirui/phpdoc-comment-vscode-plugin#6]
Hello,

I am trying to generate a docblock for a class in VS Code but I get this:

"Please select a PHP function signature"

Thanks

**Comment by AndreyChursin** [comment]
Still the same error ...
And also does not work for variables in the class! How we can fix it?))

**Comment by shishirui** [comment]
variables or classes has been supported in latest version.

**Comment by kishansuvarna09** [comment]
Got the error 'Please select a PHP function signature' while adding the doc block. Worked just fine when I set it up. Once I reopened the editor and tried executing, it shows this error. I am using the version 1.3.0 on windows 10.

**Comment by mg169706** [comment]
I'm also having this issue in v.1.3.0. There is a similar thread [here](https://github.com/shishirui/phpdoc-comment-vscode-plugin/issues/12), but the comment detailing the fix is just random words that mean nothing to anyone except the author.

**Comment by adamchemiawppl** [comment]
Hey,

Your cursor needs to be on function/class name when you click the shortcut. Then it works.

Agreed, that author's explanation is not really helpful.
